### ISSUE TITLE
No encoder set for the appender named [WEB_DEBUG_APPENDER]

### ISSUE THREAD

**Issue by haluomao** [haluomao/bugbag#4]
Logging system failed to initialize using configuration from '../conf/logback.xml'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.util.PropertySetter@1b0375b3 - A "ch.qos.logback.classic.encoder.PatternLayoutEncoder" object is not assignable to a "com.baidu.bce.plat.webframework.logging.patch.CustomLogPatternLayoutEncoder" variable.
ERROR in ch.qos.logback.core.joran.util.PropertySetter@1b0375b3 - The class "com.baidu.bce.plat.webframework.logging.patch.CustomLogPatternLayoutEncoder" was loaded by 
ERROR in ch.qos.logback.core.joran.util.PropertySetter@1b0375b3 - [org.springframework.boot.loader.LaunchedURLClassLoader@13221655] whereas object of type 
ERROR in ch.qos.logback.core.joran.util.PropertySetter@1b0375b3 - "ch.qos.logback.classic.encoder.PatternLayoutEncoder" was loaded by [org.springframework.boot.loader.LaunchedURLClassLoader@13221655].
ERROR in com.baidu.bce.plat.webframework.logging.WebDebugAppender[WEB_DEBUG_APPENDER] - No encoder set for the appender named [WEB_DEBUG_APPENDER].
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:161)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:47)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:304)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:272)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:235)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:208)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:72)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176)
	at com.baidu.bce.acupiat.mp.caseplat.CasePlatApplication.main(CasePlatApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
2020-04-01 04:36:47.023 ERROR 12429 [main] --- .b.b.p.w.e.BootstarpExceptionRunlistener : [][] bootstrap start up fail

而事实上，logback.xml里配置该字段：
```
 <if condition='"true".equals(property("logging.has_web_debug_appender"))'>
        <then>
            <appender name="WEB_DEBUG_APPENDER" class="com.baidu.bce.plat.webframework.logging.WebDebugAppender">
                <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                    <level>${logging.web_debug.level}</level>
                </filter>
                <encoder>
                    <charset>UTF-8</charset>
                    <pattern>${logging.log_pattern}</pattern>
                </encoder>
            </appender>
        </then>
    </if>
```

**Comment by haluomao** [comment]
通过追踪配置中的 xxx.plat.webframework.logging.WebDebugAppender 类，看到其中的：CustomLogPatternLayoutEncoder 和正确项目中的 PatternLayoutEncoder 不一样，可想而知，
plat.webframework版本不一致，正确配置pom.xml就正常了。
